language: minimal

services:
  - docker

script:
  - docker build -t fin1ger/autobahnkreuz-rs:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push fin1ger/autobahnkreuz-rs:latest
